### ISSUE TITLE
Fail to build on Ubuntu-18.04 64bits

### ISSUE THREAD

**Issue by mingodad** [miki151/zenon#1]
After cloning this project and trying to build it I was getting errors due to missing folders `obj` and `obj/src` after manually creating then I'm getting the error shown bellow due to missing files.

Have you forgot to commit something ?

```
clang++ -MMD -Wall -std=c++17 -Wno-sign-compare -Wno-unused-variable -Wno-shift-count-overflow -Wno-tautological-constant-out-of-range-compare -Wno-mismatched-tags -ftemplate-depth=512 -Wmissing-field-initializers -g -I/home/michal/json/include -Werror -g -I. "-DINSTALL_DIR=\"/home/mingo/dev/c/A_programming-languages/zenon\"" -include-pch obj/stdafx.h.gch -c src/lsp.cpp -o obj/src/lsp.o
src/lsp.cpp:14:10: fatal error: 'nlohmann/json.hpp' file not found
#include "nlohmann/json.hpp"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
Makefile:55: recipe for target 'obj/src/lsp.o' failed
make[1]: *** [obj/src/lsp.o] Error 1
Makefile:43: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by miki151** [comment]
Sorry, I haven't seen your issue earlier. You have to check out the library https://github.com/nlohmann/json and add modify the top line in the Makefile to point to its include directory.

**Comment by mingodad** [comment]
Thank you for reply !
